### ISSUE TITLE
Build Error - Protocol Buffers 2.0.17

### ISSUE THREAD

**Issue by normanhh3** [ederoyd46/OSMImport#4]
Attempting to build with cabal is resulting in the following output (there are several warnings, the error seems to me to be the last item):

**Environment Versions**
GHCi - 7.10.1
OS X Yosemite - 10.10.3

**Detailed Error**
```
Failed to install protocol-buffers-2.0.17
Build log ( /Users/[redacted]/Documents/OpenStreetMaps/OSMImport/platform/osmimport/logs/protocol-buffers-2.0.17.log ):
Configuring protocol-buffers-2.0.17...
Building protocol-buffers-2.0.17...
Preprocessing library protocol-buffers-2.0.17...
[ 1 of 10] Compiling Text.ProtocolBuffers.Get ( Text/ProtocolBuffers/Get.hs, dist/dist-sandbox-68ce8f44/build/Text/ProtocolBuffers/Get.o )

Text/ProtocolBuffers/Get.hs:67:1: Warning:
    The import of ‘<*>, pure, Applicative’
    from module ‘Control.Applicative’ is redundant

Text/ProtocolBuffers/Get.hs:85:1: Warning:
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()

Text/ProtocolBuffers/Get.hs:87:1: Warning:
    The import of ‘Word’ from module ‘Data.Word’ is redundant

Text/ProtocolBuffers/Get.hs:787:23: Warning:
    In the use of ‘strMsg’
    (imported from Control.Monad.Error.Class, but defined in transformers-0.4.2.0:Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

Text/ProtocolBuffers/Get.hs:803:23: Warning:
    In the use of ‘strMsg’
    (imported from Control.Monad.Error.Class, but defined in transformers-0.4.2.0:Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

Text/ProtocolBuffers/Get.hs:839:14: Warning:
    In the use of ‘S.inlinePerformIO’
    (imported from Data.ByteString.Internal):
    Deprecated: "If you think you know what you are doing, use 'unsafePerformIO'. If you are sure you know what you are doing, use 'unsafeDupablePerformIO'. If you enjoy sharing an address space with a malevolent agent of chaos, try 'accursedUnutterablePerformIO'."

Text/ProtocolBuffers/Get.hs:847:14: Warning:
    In the use of ‘S.inlinePerformIO’
    (imported from Data.ByteString.Internal):
    Deprecated: "If you think you know what you are doing, use 'unsafePerformIO'. If you are sure you know what you are doing, use 'unsafeDupablePerformIO'. If you enjoy sharing an address space with a malevolent agent of chaos, try 'accursedUnutterablePerformIO'."
[ 2 of 10] Compiling Text.ProtocolBuffers.Basic ( Text/ProtocolBuffers/Basic.hs, dist/dist-sandbox-68ce8f44/build/Text/ProtocolBuffers/Basic.o )

Text/ProtocolBuffers/Basic.hs:22:1: Warning:
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
[ 3 of 10] Compiling Text.ProtocolBuffers.Identifiers ( Text/ProtocolBuffers/Identifiers.hs, dist/dist-sandbox-68ce8f44/build/Text/ProtocolBuffers/Identifiers.o )

Text/ProtocolBuffers/Identifiers.hs:124:24:
    Ambiguous occurrence ‘uncons’
    It could refer to either ‘Text.ProtocolBuffers.Identifiers.uncons’,
                             defined at Text/ProtocolBuffers/Identifiers.hs:103:3
                          or ‘Data.List.uncons’,
                             imported from ‘Data.List’ at Text/ProtocolBuffers/Identifiers.hs:33:1-16
                             (and originally defined in ‘GHC.List’)
```

This seems to be [the file that is in question](https://hackage.haskell.org/package/protocol-buffers-2.0.17/src/Text/ProtocolBuffers/Identifiers.hs) from the hackage server source.

The [readme from the haskell package](http://code.haskell.org/protocol-buffers/README) might shed some light. :-/

This [SO article](http://stackoverflow.com/questions/2173628/haskell-ambiguous-occurrences-how-to-avoid) seems to indicate the change that needs to occur in the protocol-buffers library to clear up the compiler ambiguity.

If I knew how to just install a cabal dependency from source I would download the tarsal, make the change myself and move along.  I haven't figured out all of those steps yet.

https://www.haskell.org/cabal/users-guide/installing-packages.html#developing-with-sandboxes  seems to be a start in the right direction as regards Cabal.

I realize that this isn't a package you maintain, just have a dependency on.

I am going to reach out to the package maintainer to see if they have any pointers as well.

**Comment by ederoyd46** [comment]
Hi,

Yes I've had issues with this package before (in 7.8) and made an attempt to replace it with https://hackage.haskell.org/package/protobuf. However I had difficulty decoding some of the data, so I gave up from frustration. If you have success with the maintainer please let me know and I’ll update the package accordingly.

In the meantime the docker package still builds with GHC 7.8.

Best regards

**Comment by normanhh3** [comment]
I wonder if it is a compiler flags change that might turn off this specific issue.  I will let you know if I find something.

**Comment by ederoyd46** [comment]
I've just pushed in a patched version of protocol buffers, I'll remove it once the real version has been fixed.

**Comment by normanhh3** [comment]
I haven't heard anything back from the original package maintainer. :-(  I will try this out and see what I get!

**Comment by normanhh3** [comment]
Finally built cleanly!  Thanks so much!
