### ISSUE TITLE
OSMImport not found

### ISSUE THREAD

**Issue by joesan** [ederoyd46/OSMImport#5]
I followed the documentation on the Readme.md, but ended up with the following issue:

My-MacBook-Pro:OSMImport jothi$ OSMImport '127.0.0.1:7720' 'geo_data' '/Users/joe/Desktop/nordrhein-westfalen-latest.osm.pbf'
-bash: OSMImport: command not found

**Comment by ederoyd46** [comment]
try... 
My-MacBook-Pro:OSMImport jothi$ ./OSMImport '127.0.0.1:7720' 'geo_data' '/Users/joe/Desktop/nordrhein-westfalen-latest.osm.pbf'

**Comment by ederoyd46** [comment]
Or check that it's available on your path?
